# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 07:59
from __future__ import unicode_literals

import aldryn_bootstrap3.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_wunderground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttemperature',
            name='icon',
            field=aldryn_bootstrap3.model_fields.Icon(blank=True, default='', max_length=255),
        ),
    ]
