# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-31 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_wunderground', '0003_auto_20161010_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenttemperature',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_wunderground_currenttemperature', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
